name: arabic_open
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flip_card: ^0.7.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  video_player: ^2.8.7
  youtube_player_flutter: ^9.0.3
  firebase_core: ^3.4.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.2.0
  google_fonts: ^6.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_youtube_view: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
